site_name: Guidebook for Lingnan Students
site_url: https://zekrom88429.github.io/guidebook/

theme:
  name: material
  language: zh  # 這裡一定要維持 zh
  custom_dir: overrides
  features:
    - navigation.tabs
    - header.links.language

extra:
  alternate:
    - name: 繁體中文
      link: /guidebook/
      lang: zh-Hant
    - name: 简体中文
      link: /guidebook/zh-Hans/
      lang: zh-Hans
    - name: English
      link: /guidebook/en/
      lang: en

plugins:
  - search
  - i18n:
      languages:
        - locale: zh-Hant
          name: 繁體中文
          default: true
          build: true
        - locale: zh-Hans
          name: 简体中文
          build: true
        - locale: en
          name: English
          build: true

use_directory_urls: true

nav:
  - 首頁 Home: index.md
  - 新生須知 Guide for Freshman:
    - 該不該住校？ Shouid you apply for studnet hostel?: hostel_choice.md
  - 學習建議 Academic Advice:
    - 如何成為嶺南大學頭1%的學生 How to Beomce a Top 1% student: top1pect.md
  - 健康 Well-being:
    - 在嶺南健身 Workout in Lingnan: workout.md
  - 文集 Art Work:
    - 沒有人會記得第二名 Everyone only remembers the winner: Honor.md
    - 如何優雅地在度過四年大學生活 How to Live Gracefully Through Four Years of University: good_life.md