site_name: Guidebook for Lingnan Students
theme:
  name: material
nav:
  - 首頁: index.md
  - 繁體中文:
    - 首頁: tc/index.md
    - 如何成為嶺南大學頭1%的學生: tc/top1pect.md
  - 簡體中文:
    - 首页: sc/index.md
    - 如何成为岭南大学头1%的学生: sc/top1pect.md
  - English:
    - Home: en/index.md
    - How to become a top 1% student in Lingnan University: entop1pect.md